services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    ports:
      - "3036:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sql_circuit
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      TZ: "Asia/Tokyo"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    command: --default-authentication-plugin=mysql_native_password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8088:80"
    depends_on:
      - db